export enum NotificationType {
  BROKER_CONTACTED_YOU = "BROKER_CONTACTED_YOU",
  PHOTOS_DOWNLOADED = "PHOTOS_DOWNLOADED",
  PROPERTY_EXPIRING_TOMORROW = "PROPERTY_EXPIRING_TOMORROW",
  PROPERTY_EXPIRED = "PROPERTY_EXPIRED",
  PROPERTY_RENEWED = "PROPERTY_RENEWED",
  PROPERTY_VERIFIED = "PROPERTY_VERIFIED",
}
